import PDFDocument from "pdfkit";

interface DashboardPdfInput {
  tenantName: string;
  generatedFor: string;
  generatedAt: Date;
  kpis: {
    totalPipeline: number;
    weightedPipeline: number;
    openOpportunities: number;
    closedWonRevenue: number;
    winRate: number;
    avgOpportunitySize: number;
    totalGrossMargin?: number;
    totalExpectedMargin?: number;
    totalBottomLineCost?: number;
  };
  charts: {
    pipelineByStage: { stageName: string; count: number; amount: number }[];
    revenueByMonth: { month: string; revenue: number }[];
  };
}

function money(n: number) {
  try {
    return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(n);
  } catch {
    return `₹${n.toFixed(0)}`;
  }
}

function drawTable(doc: PDFKit.PDFDocument, headers: string[], rows: string[][], colWidths: number[], startX = 50) {
  let y = doc.y + 4;
  doc.fontSize(9).fillColor("#9ca3af");
  let x = startX;
  headers.forEach((h, i) => {
    doc.text(h, x, y, { width: colWidths[i] });
    x += colWidths[i];
  });
  y += 14;
  doc.moveTo(startX, y).lineTo(startX + colWidths.reduce((a, b) => a + b, 0), y).strokeColor("#e5e7eb").stroke();
  y += 8;

  for (const row of rows) {
    x = startX;
    doc.fontSize(10).fillColor("#111827");
    row.forEach((cell, i) => {
      doc.text(cell, x, y, { width: colWidths[i] });
      x += colWidths[i];
    });
    y += 18;
  }
  doc.y = y + 6;
}

// Generates a tabular PDF summary of dashboard KPIs and charts in memory, returned as a Buffer.
// pdfkit has no native chart-rendering support, so charts are rendered as data tables rather than images.
export function generateDashboardPdf(input: DashboardPdfInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc.fontSize(20).fillColor("#0f1a17").text(input.tenantName);
    doc.moveDown(0.2);
    doc.fontSize(10).fillColor("#6b7280").text("Dashboard Report");
    doc.moveDown(0.3);
    doc.fontSize(9).fillColor("#9ca3af").text(`Generated for ${input.generatedFor} on ${input.generatedAt.toLocaleString()}`);
    doc.moveDown(1.2);

    // KPI summary
    doc.fontSize(13).fillColor("#0f1a17").text("Key Metrics");
    doc.moveDown(0.5);
    const kpiRows: [string, string][] = [
      ["Total Pipeline", money(input.kpis.totalPipeline)],
      ["Weighted Pipeline", money(input.kpis.weightedPipeline)],
      ["Open Opportunities", String(input.kpis.openOpportunities)],
      ["Closed Won Revenue", money(input.kpis.closedWonRevenue)],
      ["Win Rate", `${Math.round(input.kpis.winRate * 100)}%`],
      ["Avg Opportunity Size", money(input.kpis.avgOpportunitySize)],
      ["Margin Value", money((input.kpis.totalGrossMargin || 0) + (input.kpis.totalExpectedMargin || 0))],
      ["Cost Incurred to Company", money(input.kpis.totalBottomLineCost || 0)],
    ];
    for (const [label, value] of kpiRows) {
      const y = doc.y;
      doc.fontSize(10).fillColor("#6b7280").text(label, 50, y, { width: 220 });
      doc.fontSize(10).fillColor("#111827").text(value, 280, y, { width: 180, align: "right" });
      doc.moveDown(0.6);
    }
    doc.moveDown(1);

    // Pipeline by stage
    doc.fontSize(13).fillColor("#0f1a17").text("Pipeline by Stage");
    if (input.charts.pipelineByStage.length === 0) {
      doc.fontSize(10).fillColor("#6b7280").text("No open opportunities.");
    } else {
      drawTable(
        doc,
        ["Stage", "Count", "Value"],
        input.charts.pipelineByStage.map((s) => [s.stageName, String(s.count), money(s.amount)]),
        [250, 100, 145]
      );
    }
    doc.moveDown(1);

    // Revenue by month
    doc.fontSize(13).fillColor("#0f1a17").text("Revenue by Month (last 6 months)");
    drawTable(
      doc,
      ["Month", "Revenue"],
      input.charts.revenueByMonth.map((m) => [m.month, money(m.revenue)]),
      [250, 245]
    );

    doc.moveDown(2);
    doc.fontSize(8).fillColor("#9ca3af").text("Generated by CRM. Figures reflect your role's data visibility scope at the time of export.", 50, 760, { width: 495, align: "center" });

    doc.end();
  });
}
