import PDFDocument from "pdfkit";

interface QuotePdfInput {
  quoteNumber: string;
  quoteDate: Date;
  expirationDate: Date | null;
  status: string;
  currency: string;
  discountPct: number;
  taxPct: number;
  amount: number;
  account: { name: string };
  deal: { name: string };
  owner: { firstName: string; lastName: string; email?: string };
  lineItems: { product: { name: string; sku?: string | null }; quantity: number; unitPrice: number; discountPct: number; total: number }[];
  tenantName: string;
}

function money(n: number, currency: string) {
  try {
    return new Intl.NumberFormat("en-US", { style: "currency", currency }).format(n);
  } catch {
    return `${currency} ${n.toFixed(2)}`;
  }
}

// Generates a clean, professional quote PDF in memory and returns it as a Buffer.
export function generateQuotePdf(input: QuotePdfInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc.fontSize(20).fillColor("#0f1a17").text(input.tenantName, { continued: false });
    doc.moveDown(0.2);
    doc.fontSize(10).fillColor("#6b7280").text("Sales Quote");
    doc.moveDown(1);

    doc.fontSize(22).fillColor("#17976f").text(`Quote ${input.quoteNumber}`);
    doc.moveDown(0.5);

    doc.fontSize(10).fillColor("#374151");
    doc.text(`Status: ${input.status}`);
    doc.text(`Quote date: ${input.quoteDate.toLocaleDateString()}`);
    if (input.expirationDate) doc.text(`Valid until: ${input.expirationDate.toLocaleDateString()}`);
    doc.moveDown(1);

    // Parties
    const colY = doc.y;
    doc.fontSize(9).fillColor("#9ca3af").text("PREPARED FOR", 50, colY);
    doc.fontSize(12).fillColor("#111827").text(input.account.name, 50, colY + 14);

    doc.fontSize(9).fillColor("#9ca3af").text("PREPARED BY", 320, colY);
    doc.fontSize(12).fillColor("#111827").text(`${input.owner.firstName} ${input.owner.lastName}`, 320, colY + 14);
    if (input.owner.email) doc.fontSize(9).fillColor("#6b7280").text(input.owner.email, 320, colY + 30);

    doc.moveDown(3);
    doc.fontSize(9).fillColor("#9ca3af").text(`RELATED DEAL: ${input.deal.name}`);
    doc.moveDown(1);

    // Line items table
    const tableTop = doc.y + 10;
    const colX = { name: 50, qty: 300, price: 360, disc: 430, total: 480 };
    doc.fontSize(9).fillColor("#9ca3af");
    doc.text("ITEM", colX.name, tableTop);
    doc.text("QTY", colX.qty, tableTop);
    doc.text("PRICE", colX.price, tableTop);
    doc.text("DISC%", colX.disc, tableTop);
    doc.text("TOTAL", colX.total, tableTop);
    doc.moveTo(50, tableTop + 14).lineTo(545, tableTop + 14).strokeColor("#e5e7eb").stroke();

    let y = tableTop + 22;
    if (input.lineItems.length) {
      for (const item of input.lineItems) {
        doc.fontSize(10).fillColor("#111827");
        doc.text(item.product.name, colX.name, y, { width: 240 });
        doc.text(String(item.quantity), colX.qty, y);
        doc.text(money(item.unitPrice, input.currency), colX.price, y);
        doc.text(`${item.discountPct}%`, colX.disc, y);
        doc.text(money(item.total, input.currency), colX.total, y);
        y += 20;
      }
    } else {
      doc.fontSize(10).fillColor("#6b7280").text("Single line item — see deal amount below.", colX.name, y);
      y += 20;
    }

    doc.moveTo(50, y + 4).lineTo(545, y + 4).strokeColor("#e5e7eb").stroke();
    y += 16;

    doc.fontSize(10).fillColor("#374151");
    doc.text(`Discount: ${input.discountPct}%`, 400, y, { width: 145, align: "right" });
    y += 16;
    doc.text(`Tax: ${input.taxPct}%`, 400, y, { width: 145, align: "right" });
    y += 20;

    doc.fontSize(14).fillColor("#0f1a17").text(`Total: ${money(input.amount, input.currency)}`, 350, y, { width: 195, align: "right" });

    doc.moveDown(4);
    doc.fontSize(8).fillColor("#9ca3af").text("Generated by Ledger CRM. This is not a binding contract until signed by both parties.", 50, 760, { width: 495, align: "center" });

    doc.end();
  });
}
